name: "Twingate Connector"
description: "One click Twingate Connector deployment"
url: https://github.com/grahamulator/ha-addons/tree/main/tg_connector
version: "0.2.10"
slug: "tg_connector"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
host_network: true
docker_api: true
full_access: true
schema:
  network_slug: str
  connector_name: str
  access_token: str
  refresh_token: str